WITH ENG_DATA AS (
    SELECT
        NAME AS ENG,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN_ENG
    FROM
        PROFESSION_DATA
    WHERE 
        PROFESSION = 'ENG'
)
,DOCTOR_DATA AS (
    SELECT
        NAME AS DOCTOR,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN_DOCTOR
    FROM
        PROFESSION_DATA
    WHERE 
        PROFESSION = 'DOCTOR'
)
,NURSE_DATA AS (
    SELECT
        NAME AS NURSE,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN_NURSE
    FROM
        PROFESSION_DATA
    WHERE 
        PROFESSION = 'NURSE'
)
SELECT
  E.ENG, D.DOCTOR, N.NURSE
FROM
  ENG_DATA E
LEFT JOIN
  DOCTOR_DATA D
  ON E.RN_ENG = D.RN_DOCTOR
LEFT JOIN
  NURSE_DATA N
  ON E.RN_ENG = N.RN_NURSE;